# Base image https://hub.docker.com/u/rocker/
FROM rocker/r-base:latest

# Set working directory
WORKDIR /App

# Update image
RUN apt-get update -qq -y

## create and populate directory
RUN mkdir -p /code
COPY --from=build-env /App/* ./code/

## copy files
COPY requirements.R /code/install_packages.R
COPY codepull.sh /code/codepull.sh

## install R-packages
RUN Rscript /code/install_packages.R
RUN sh /code/codepull.sh

## run the script
# CMD Rscript /code/myScript.R